### ISSUE TITLE
Typed subscribe stream event data

### ISSUE THREAD

**Issue by wbobeirne** [RadarTech/lnrpc#29]
It would be excellent of methods like `subscribeInvoices` or `subscribeTransactions` had typed data for their events. It looks like the default Readable class doesn't have a way of providing types for instances of it, so I'm not sure how this is done, but it'd certainly make working with these streams a lot easier.

**Comment by cavanmflynn** [comment]
Good idea. We can declare generic streams that will allow us to feed the stream types to the listeners.

**Comment by cavanmflynn** [comment]
Typed streams have been released in [v0.5.2-beta.5](https://github.com/RadarTech/lnrpc/releases/tag/v0.5.2-beta.5).

**Comment by wbobeirne** [comment]
Y'all work fast, this is amazing. Thanks for the quick work!
