### ISSUE TITLE
CloseChannel requires both bytes and str txid

### ISSUE THREAD

**Issue by wbobeirne** [RadarTech/lnrpc#54]
The current argument interface for closing a channel is
```ts
export interface ChannelPoint {
  fundingTxidBytes: Buffer | string;
  fundingTxidStr: string;
  outputIndex: number;
}
```
This should probably be either bytes or string, not both.

**Comment by cavanmflynn** [comment]
A fix has been published in [v0.8.0-beta.0](https://github.com/RadarTech/lnrpc/releases/tag/v0.8.0-beta.0).
