### ISSUE TITLE
Not working on Raspberry Pi Zero

### ISSUE THREAD

**Issue by Janaka-Steph** [RadarTech/lnrpc#68]
Hello, 

I wanted to run a web app that uses this library on a Raspberry Pi Zero but I have issues. I got a `Illegal instruction` error. Apparently it is because of grpc. 
So this past night I runned `npm rebuild --build-from-source=grpc`, but still got an error `...node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8`.
I don't think there is a good solution for this, I am just writing this issue in case someone faces it.

**Comment by cavanmflynn** [comment]
I attempted to drop `grpc` in favor of `@grpc/grpc-js` about a month ago, but it introduced more issues than `grpc`. I can re-attempt as `grpc-js` becomes more stable.

**Comment by cavanmflynn** [comment]
@Janaka-Steph Closing this as `grpc` was replaced by `@grpc/grpc-js` in [v0.11.1-beta.1](https://github.com/RadarTech/lnrpc/releases/tag/v0.11.1-beta.1).
